name: Build and Deploy Web App

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Flutter SDK
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

    - name: Configure Flutter Web
      run: |
        flutter config --enable-web
        flutter create --platforms web .

    - name: Fetch Dependencies
      run: flutter pub get

    - name: Build Web App
      run: flutter build web --release --no-pub --no-tree-shake-icons

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/web

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
